import type { Metadata } from "next";
import { Roboto, Nunito } from "next/font/google";
import { Header } from "@/components";
import Providers from "@/providers";
import { i18n } from "@/i18n-config";

import "../globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "700"],
  display: "swap",
  variable: "--font-title",
});

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} ${nunito.variable}`}>
        <Providers>
          <div className="flex min-h-screen flex-col overflow-hidden">
            <Header />
            <main className="grow">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}