import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/providers";
import { Header } from "@/sections/Header";
import { ScrollToTop } from "@/ui";
import { ReactElement } from "react";
import { getStaticParams } from "@/lib/i18n/server";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  params: { locale },
  children,
}: {
  params: { locale: string };
  children: ReactElement;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers locale={locale}>
          <div className="relative flex min-h-screen flex-col overflow-hidden">
            <Header />
            <main className="grow">{children}</main>
          </div>
          <ScrollToTop />
        </Providers>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return getStaticParams();
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
